variables:
# Azure Resource Manager connection created during pipeline creation
azureServiceConnectionId: 'Sandbox connection'

# Web app name
webAppName: 'webapp-14681'

# Agent VM image name
vmImageName: 'ubuntu-latest'

# Environment name
environmentName: 'webapp-14681'

# Project root folder.
projectRoot: $(python-sample-flask-tutorial)

# Python version: 3.7. Change this to match the Python runtime version running on your web app.
pythonVersion: '3.7'

- job: BuildJob
  pool:
    vmImage: $(vmImageName)

# - task: UsePythonVersion@0
#     inputs:
#       versionSpec: '$(3.7)'
#       displayName: 'Use Python $(pythonVersion)'

- script: |
      python -m venv antenv
      source antenv/bin/activate
      python -m pip install --upgrade pip
      pip install setup
      pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
    workingDirectory: $(projectRoot)
    displayName: "Install requirements"

- task: ArchiveFiles@2
     displayName: 'Archive files'
     inputs:
       rootFolderOrFile: '$(projectRoot)'
       includeRootFolder: false
       archiveType: zip
       archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
       replaceExistingArchive: true

   - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
     displayName: 'Upload package'
     artifact: drop

dependsOn: Build
condition: succeeded()

- deployment: DeploymentJob
  pool:
    vmImage: $(vmImageName)
  environment: $(environmentName)

strategy:
    runOnce:
      deploy:
        steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '$(pythonVersion)'
          displayName: 'Use Python version'

- task: AzureWebApp@1
   displayName: 'Deploy Azure Web App'
   inputs:
      azureSubscription: $(azureServiceConnectionId)
      appName: $(webAppName)
      package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip